# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: External search engine connectors
repo_name: search-engine
repo_slug: search-engine
repo_website: https://github.com/OCA/search-engine
travis_apt_packages: []
travis_apt_sources: []
