[project]
name = "odoo-addons-oca-search-engine"
version = "18.0.20260527.0"
dependencies = [
    "odoo-addon-connector_elasticsearch==18.0.*",
    "odoo-addon-connector_search_engine==18.0.*",
    "odoo-addon-connector_typesense==18.0.*",
    "odoo-addon-search_engine_serializer_pydantic==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
